Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Arriendos-Backend, pull requests merged in 2023-12, with the labels that each got.

#343 Corrección de edición de records de inmuebles
  rooms/signals.py
Labels: bug

#344 Corrección de listado de requisitos requeridos
  requirements/views.py
Labels: refactoring

#345 Actualización de carga de datos de Propiedades
  initial_data/properties_data.py
Labels: enhancement

#347 API para eliminar clientes
  customers/permissions.py
  customers/views.py
Labels: enhancement

#351 Adición de Fecha de solicitud y retorno de garantía
  financials/views.py
  leases/migrations/0002_rental_warranty_return_request_and_more.py
  leases/models.py
Labels: enhancement

#353 Correción de carga de datos de sub ambientes
  customers/views.py
  initial_data/load_data.py
Labels: enhancement

#358 Creación de reporte por rango de fechas y estado
  leases/function.py
  leases/serializer.py
  leases/urls.py
  leases/views.py
  requirements.txt
Labels: enhancement

#359 Solución de los listado de registros de customers, products y requirements
  customers/views.py
  products/views.py
  requirements/views.py
Labels: bug

#361 API para buscar productos
  products/urls.py
  products/views.py
Labels: enhancement

#363 Adición de busqueda de Customer type
  customers/views.py
  requirements/views.py
Labels: enhancement

#364 Paginado para API para buscar productos
  products/urls.py
  products/views.py
Labels: enhancement, refactoring

#366 Adición del nup a formularios
  financials/function.py
  financials/templates/devolucion_de_garantia.html
  financials/templates/ejecucion_de_garantia.html
  leases/function.py
  leases/templates/entrega_y_recepcion_de_ambientes.html
  leases/templates/horas_extra.html
  requirements/function.py
  requirements/templates/reserva.html
Labels: enhancement

#368 Validación de eliminación de cliente si tiene un alquiler en proceso
  customers/views.py
Labels: enhancement

#370 Despliegue del estado del alquiler en el calendario
  leases/views.py
Labels: enhancement

#372 Filtro de productos buscando inmuebles, ambiente, tarifa y rango de h…
  products/views.py
Labels: enhancement

#373 corrección en el despliegue de alquiler en el calendario
  leases/views.py
Labels: refactoring

#375 API para listar los alquileres
  leases/views.py
Labels: enhancement

#377 Paginado de API para listar los alquileres
  leases/views.py
Labels: enhancement

#379 Filtro de API para listar los alquileres
  leases/views.py
Labels: enhancement

#381 API para editar pagos
  financials/urls.py
  financials/views.py
Labels: enhancement

#383 API para editar garantías
  financials/urls.py
  financials/views.py
Labels: enhancement

#385 Adición de formato a formulario de reserva efectiva
  requirements/function.py
  requirements/logo.jpg
  requirements/templates/reserva.html
Labels: documentation

#386 API para listar alquileres
  leases/urls.py
  leases/views.py
Labels: enhancement

#388 Adición de formato a formulario de entrega y recepción de ambientes y horas extra
  leases/logo.jpg
  leases/templates/entrega_y_recepcion_de_ambientes.html
  leases/templates/horas_extra.html
Labels: enhancement

#390 Generación de formularios y reporte
  leases/function.py
  leases/views.py
Labels: enhancement

#392 Adición de formato a formularios de financials
  financials/templates/devolucion_de_garantia.html
  financials/templates/ejecucion_de_garantia.html
  financials/templates/solicitud_devolucion_de_garantia.html
Labels: enhancement

#394 API para obtener la información de un registro de garantía y de un pago
  financials/views.py
Labels: enhancement

#396 Generación de formularios de garantía
  financials/function.py
  financials/logo.jpg
  financials/views.py
Labels: enhancement

#398 Adición de fecha a retorno de garantía
  financials/views.py
  leases/templates/horas_extra.html
Labels: enhancement

#401 Permisos para la interfaz de ediciones de alquileres
  financials/permissions.py
  financials/views.py
  leases/views.py
Labels: enhancement

#402 Validación de generación de formularios de aplicación financials
  financials/views.py
  leases/templates/entrega_y_recepcion_de_ambientes.html
Labels: enhancement

#403 Cargado de datos de sub_ambientes
  initial_data/sub_rooms_data.py
Labels: enhancement

#405 Adición de fecha para retorno de la garantía
  financials/views.py
Labels: enhancement

#407 Corrección de Bugs del listado de alquileres
  leases/views.py
Labels: bug

#409 Corrección de header de los formularios
  financials/templates/devolucion_de_garantia.html
  financials/templates/ejecucion_de_garantia.html
  financials/templates/solicitud_devolucion_de_garantia.html
  financials/views.py
  leases/templates/entrega_y_recepcion_de_ambientes.html
  leases/templates/horas_extra.html
  leases/views.py
  requirements/templates/reserva.html
Labels: enhancement

#410 Corrección function de requirements
  requirements/function.py
Labels: duplicate, enhancement

#412 API para mostrar el monto de garantía para productos individuales
  financials/views.py
Labels: enhancement

#413 Corrección de formulario de horas extra
  leases/views.py
Labels: bug, enhancement

#415 API para editar los pagos de alquileres
  financials/views.py
Labels: enhancement

#417 Correción de formato de fechas en reporte
  financials/function.py
  leases/function.py
  leases/templates/horas_extra.html
Labels: bug, enhancement
