Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Arriendos-Backend, pull requests merged in 2023-11, with the labels that each got.

#205 Adición de address modelo y migraciones
  rooms/migrations/0004_property_address.py
  rooms/models.py
  rooms/serializers.py
  rooms/views.py
Labels: enhancement

#207 Formulario de entrega y recepción de ambientes
  leases/function.py
  leases/serializer.py
  leases/templates/entrega_y_recepcion_de_ambientes.html
  leases/urls.py
  leases/views.py
Labels: enhancement

#209 Creación de modelo y migración de la tabla Horas extra aplicadas
  leases/migrations/0006_additional_hour_applied.py
  leases/models.py
Labels: enhancement

#211 Reserves
  leases/serializer.py
  leases/urls.py
  leases/views.py
Labels: enhancement

#213 Formulario de conformidad para devolución de garantía
  financials/function.py
  financials/templates/devolucion_de_garantia.html
  financials/urls.py
  financials/views.py
Labels: enhancement

#215 Formulario de horas extra
  leases/function.py
  leases/templates/horas_extra.html
  leases/views.py
Labels: enhancement

#217 Corrección de valores decimales en los registros de Pagos
  financials/views.py
Labels: refactoring

#218 Re estructuración de solicitud de reserva
  customers/serializer.py
  requirements/function.py
  requirements/templates/reserva.html
  requirements/views.py
Labels: enhancement, refactoring

#220 Adición de numero de sub ambiente a formulario de entrega de ambientes
  leases/templates/entrega_y_recepcion_de_ambientes.html
Labels: enhancement

#222 API Para listar horas extra por arriendo
  leases/urls.py
  leases/views.py
  rooms/models.py
Labels: enhancement

#224 APi Para listar garantías
  financials/views.py
Labels: enhancement

#225 Correción de API para listar las horas extras
  leases/views.py
Labels: refactoring

#227 Validación de sólo arriendos no cancelados
  leases/templates/entrega_y_recepcion_de_ambientes.html
  leases/views.py
Labels: enhancement

#231 API para eliminar el último registro de Garantía
  financials/urls.py
  financials/views.py
Labels: enhancement

#229 Edición de contactos en CRUD Customers
  customers/views.py
Labels: enhancement

#233 Validaciones para cambio de estado
  leases/views.py
Labels: enhancement

#235 Adición de numero correlativo a Rental
  leases/migrations/0007_rental_contract_number.py
  leases/models.py
Labels: enhancement

#239 Asignación de usuarios y ambientes corrección
  financials/function.py
  requirements/templates/reserva.html
  users/views.py
Labels: bug, enhancement

#240 Refactorización de validaciones para mostrar daños de garantía
  financials/views.py
Labels: bug, refactoring

#241 Adición de correlativo y tipificación en listado de Garantía
  financials/views.py
Labels: refactoring

#243 API para eliminar el último registro de hora extra
  leases/views.py
Labels: enhancement

#244 API para eliminar el último registro de hora extra
  leases/urls.py
Labels: enhancement

#246 Despliegue del mensaje de validación de posible producto
  products/views.py
Labels: refactoring

#248 Búsqueda de clientes closes#247
  customers/views.py
  requirements/views.py
Labels: enhancement

#249 correccion de nombre de url de posible producto
  products/urls.py
Labels: refactoring

#250 corrección de respuesta de API de posible producto
  products/views.py
Labels: refactoring

#252 Instalación de DRF Spectacular
  Arriendos_Backend/urls.py
  requirements.txt
Labels: documentation, enhancement

#254 Documentación de APIs con Swagger
  Arriendos_Backend/urls.py
  requirements.txt
Labels: documentation, enhancement

#256 Adición de documentación Swagger a Customers
  customers/urls.py
  customers/views.py
Labels: documentation, enhancement

#258 PERMISOS PARA LA APLICACIÓN ROOMS
  rooms/permissions.py
  rooms/urls.py
  rooms/views.py
Labels: enhancement

#260 Adición de Swagger a la aplicación Products
  products/serializers.py
  products/urls.py
  products/views.py
Labels: documentation, enhancement

#264 Adición de Permisos para APIS de la aplicación clientes
  customers/permissions.py
  customers/views.py
Labels: enhancement

#262 Adición de Swagger a Rooms
  rooms/views.py
Labels: documentation, enhancement

#266 Adición de Swagger a Requirements
  leases/serializer.py
  products/serializers.py
  requirements/views.py
Labels: documentation, enhancement

#268 Permisos para la aplicación Products
  products/permissions.py
  products/views.py
Labels: enhancement

#270 Adición de Swagger a Leases
  financials/views.py
  leases/views.py
Labels: documentation, enhancement

#272 Permisos para aplicación Requirements
  requirements/permissions.py
  requirements/views.py
Labels: enhancement

#274 Permisos para aplicación Financials
  financials/permissions.py
  financials/views.py
Labels: enhancement

#276 Adición de Swagger a Login y Users
  login/urls.py
  login/views.py
  users/views.py
Labels: documentation, enhancement

#278 Adición de descripción a formulario de horas extra
  leases/function.py
  leases/templates/horas_extra.html
  requirements/templates/reserva.html
Labels: enhancement

#280 Permisos para la aplicación Leases
  leases/permissions.py
  leases/views.py
Labels: enhancement

#284 Creación de Modelo y migración para almacenar Records
  users/migrations/0002_record.py
  users/models.py
Labels: enhancement

#286 Adición de Records a user
  requirements.txt
  users/apps.py
  users/signals.py
  users/views.py
Labels: enhancement

#288 Formato de Records User
  users/signals.py
Labels: documentation, enhancement

#289 Refactorización de Modelo y migración para almacenar Records
  users/migrations/0003_alter_record_action_alter_record_detail_and_more.py
  users/models.py
Labels: enhancement, refactoring

#293 Records para aplicación Rooms
  rooms/apps.py
  rooms/signals.py
  rooms/views.py
Labels: enhancement

#295 Adición de Records a Requirements
  requirements/apps.py
  requirements/signals.py
  requirements/views.py
Labels: documentation, enhancement

#298 Records para aplicación Financials
  financials/apps.py
  financials/signals.py
  financials/views.py
Labels: enhancement

#300 Adición de Records a Products
  products/apps.py
  products/signals.py
  products/views.py
Labels: documentation, enhancement

#302 Reserves
  customers/apps.py
  customers/signals.py
  customers/views.py
Labels: enhancement

#304 Carga de datos iniciales para Properies y para Rooms
  initial_data/load_data.py
  initial_data/properties_data.py
  initial_data/rooms_data.py
Labels: enhancement

#305 Records a Products
  products/signals.py
  requirements/signals.py
Labels: documentation, duplicate, enhancement

#307 Adición de records a Plans
  plans/apps.py
  plans/signals.py
  plans/views.py
Labels: documentation, enhancement

#309 Validación de formulario de devolución de garantía
  financials/views.py
Labels: enhancement

#311 Datos iniciales para carga de datos
  initial_data/customer_type.py
  initial_data/rates_data.py
  initial_data/requirements_data.py
Labels: enhancement

#312 Rafactorizacion de carga de datos iniciales
  initial_data/hour_range_data.py
  initial_data/load_data.py
  initial_data/properties_data.py
  initial_data/rooms_data.py
Labels: enhancement, refactoring

#314 Reserves
  customers/signals.py
  financials/signals.py
  leases/signals.py
  plans/signals.py
  products/signals.py
  requirements/signals.py
  rooms/signals.py
  users/migrations/0004_record_instance_id.py
  users/models.py
  users/signals.py
Labels: enhancement

#316 Carga de datos iniciales para subambientes, precios de horas adicionales y productos
  initial_data/additional_hour_price_data.py
  initial_data/load_data.py
  initial_data/products_data.py
  initial_data/sub_enviroment_data.py
Labels: enhancement

#320 Adición de department a formularios
  financials/function.py
  financials/templates/solicitud_devolucion_de_garantia.html
  financials/views.py
  leases/templates/entrega_y_recepcion_de_ambientes.html
  requirements/views.py
Labels: enhancement

#324 Carga de datos iniciales para estados de arriendo
  initial_data/load_data.py
  initial_data/products_data.py
  initial_data/rooms_data.py
  initial_data/state_data.py
  leases/views.py
Labels: enhancement, refactoring

#326 Datos de carga inicial de Plans
  initial_data/plans_data.py
Labels: enhancement

#328 API para identificar si el cliente es policía consumiendo el microser…
  customers/urls.py
  customers/views.py
Labels: enhancement

#330 Reestructuración de Modelo Sub ambientes
  rooms/migrations/0006_rename_sub_environment_sub_room.py
  rooms/models.py
  rooms/permissions.py
  rooms/serializers.py
  rooms/signals.py
  rooms/urls.py
  rooms/views.py
Labels: enhancement

#332 Adición de sub ambientes a formularios
  financials/templates/devolucion_de_garantia.html
  leases/templates/entrega_y_recepcion_de_ambientes.html
  leases/templates/horas_extra.html
  leases/views.py
Labels: enhancement

#334 Datos de carga de sub room
  initial_data/load_data.py
  initial_data/sub_room_data.py
Labels: documentation, duplicate

#335 Actualización de README
  README.md
  requirements.txt
Labels: documentation

#337 Docker File y documentación para construir la imagen y contenedor
  Dockerfile
  README.md
Labels: documentation

#338 Formato de settings
  .gitignore
  Arriendos_Backend/settings.py
Labels: enhancement

#340 Migraciones de los modelos
  customers/migrations/0001_initial.py
  customers/migrations/0002_alter_customer_institution_name.py
  financials/migrations/0001_initial.py
  financials/migrations/0002_warranty_movement_voucher_number.py
  financials/migrations/0003_alter_payment_detail_alter_payment_voucher_number_and_more.py
  leases/migrations/0001_initial.py
  leases/migrations/0002_rental_is_plan_rental_state_delete_rental_state.py
  leases/migrations/0003_rental_initial_total_rental_plan_and_more.py
  leases/migrations/0004_rental_year.py
  leases/migrations/0005_remove_rental_is_plan_remove_rental_year.py
  leases/migrations/0006_additional_hour_applied.py
  leases/migrations/0007_rental_contract_number.py
  leases/migrations/0008_alter_additional_hour_applied_description_and_more.py
  login/migrations/__init__.py
  plans/migrations/0001_initial.py
  plans/migrations/0002_remove_plan_payment_plan.py
  products/migrations/0001_initial.py
  products/migrations/0002_price_additional_hour.py
  products/migrations/0003_alter_product_day.py
  requirements/migrations/0001_initial.py
  requirements/migrations/0002_requirement_delivered_delete_planrequirement.py
  rooms/migrations/0001_initial.py
  rooms/migrations/0002_sub_environment.py
  rooms/migrations/0003_sub_environment_quantity.py
  rooms/migrations/0004_property_address.py
  rooms/migrations/0005_property_department.py
  rooms/migrations/0006_rename_sub_environment_sub_room.py
  users/migrations/0001_initial.py
  users/migrations/0002_record.py
  users/migrations/0003_alter_record_action_alter_record_detail_and_more.py
  users/migrations/0004_record_instance_id.py
Labels: enhancement
