Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Arriendos-Backend, pull requests merged in 2023-10, with the labels that each got.

#81 API para edición de productos y actualización de precio
  products/views.py
Labels: enhancement

#83 API clientes y contactos segun la tarifa y tipo cliente
  customers/migrations/0001_initial.py
  customers/models.py
  customers/serializer.py
  customers/urls.py
  customers/views.py
Labels: enhancement

#85 Creacion aplicacion Leases y API de Selected Product
  Arriendos_Backend/urls.py
  leases/__init__.py
  leases/admin.py
  leases/apps.py
  leases/migrations/0001_initial.py
  leases/migrations/__init__.py
  leases/models.py
  leases/serializer.py
  leases/tests.py
  leases/urls.py
  leases/views.py
  requirements/migrations/0001_initial.py
  requirements/migrations/__init__.py
  requirements/views.py
Labels: enhancement

#87 Carga de datos inicial de tarifas y rango de horas
  products/fixtures/initial_data_days.json
  products/fixtures/initial_data_hour_range.json
  products/fixtures/initial_data_rate.json
Labels: enhancement

#89 Carga de datos de tipo de clientes
  customers/fixtures/initial_data_customer_type.json
Labels: enhancement

#91 Carga de datos de requisitos
  requirements/fixtures/initial_data_requirements.json
Labels: enhancement

#93 Manual de instalación del proyecto
  README.md
Labels: documentation

#97 API para listar los posibles productos seleccionables
  products/urls.py
  products/views.py
Labels: enhancement

#99 APIs Leases get y post
  leases/models.py
  leases/serializer.py
  leases/urls.py
  leases/views.py
Labels: enhancement

#104 Reestructuración de APIs de arriendos
  leases/views.py
Labels: enhancement

#106 Reestructuración de aplicación requirements y APIs de requisitos
  plans/urls.py
  plans/views.py
  requirements/migrations/0001_initial.py
  requirements/models.py
  requirements/urls.py
  requirements/views.py
Labels: enhancement

#107 refactorización de modelo rango de hora
  products/fixtures/initial_data_hour_range.json
  products/migrations/0001_initial.py
  products/models.py
Labels: enhancement

#110 API para edicion de customer y contacts
  customers/urls.py
  customers/views.py
Labels: enhancement

#112 API Leases post reestructuración event_type
  leases/views.py
Labels: enhancement

#114 Carga de datos inicial de estados de arriendo
  leases/fixtures/initial_data_state.json
Labels: enhancement

#115 Migración products con rango de horas
  products/migrations/0001_initial.py
Labels: duplicate

#116 Visualización de grupo en rooms
  rooms/models.py
  rooms/views.py
Labels: enhancement

#118 API mostrar el listado de requisito según el arriendo
  requirements/serializer.py
  requirements/urls.py
  requirements/views.py
Labels: enhancement

#120 APIs Leases con Rooms y fechas
  leases/models.py
  leases/serializer.py
  leases/views.py
Labels: enhancement

#121 adición de campo next_state en estados de arriendo
  leases/models.py
Labels: enhancement

#122 Migraciones de Leases
  leases/migrations/0001_initial.py
Labels: enhancement

#124 Refactorizacíón de modelo Rental
  leases/migrations/0002_rental_is_plan_rental_state_delete_rental_state.py
  leases/models.py
Labels: enhancement

#125 Reserves
  leases/migrations/0002_rental_is_plan_rental_state_delete_rental_state.py
  leases/models.py
Labels: enhancement

#127 API para obtener el estado del arriendo y su siguiente posible estado
  leases/urls.py
  leases/views.py
Labels: enhancement

#128 respuesta de API de estado y siguiente posible estado con nombres de …
  leases/views.py
Labels: refactoring

#132 API para listar todos los estados de arriendo
  leases/urls.py
  leases/views.py
Labels: enhancement

#134 Adición de tabla Requisitos entregados
  plans/urls.py
  plans/views.py
  requirements/migrations/0002_requirement_delivered_delete_planrequirement.py
  requirements/models.py
  requirements/serializer.py
  requirements/views.py
Labels: enhancement

#136 Reestructuración modelo y migración de Plans y Rental
  leases/migrations/0003_rental_initial_total_rental_plan_and_more.py
  leases/models.py
  plans/migrations/0002_remove_plan_payment_plan.py
  plans/models.py
Labels: enhancement

#137 API para ver el listado de estados del arriendo
  leases/urls.py
  leases/views.py
Labels: enhancement

#139 API Selected products con precios y total inicial
  leases/serializer.py
  leases/urls.py
  leases/views.py
Labels: enhancement

#141 Refactorización de API Plans
  plans/serializer.py
  plans/urls.py
  plans/views.py
Labels: enhancement

#144 API para cambiar el estado de arriendo a reservado
  Arriendos_Backend/util.py
  leases/urls.py
  leases/views.py
Labels: enhancement

#146 API para obtener la información de cada Arriendo
  leases/urls.py
  leases/views.py
Labels: enhancement

#149 Adición de precio a posible productos
  products/views.py
Labels: enhancement

#153 API para registrar los requisitos entregados
  requirements/urls.py
  requirements/views.py
Labels: enhancement, refactoring

#155 API para cambiar el estado del arriendo
  leases/urls.py
  leases/views.py
Labels: enhancement

#156 Correcion de nombre de variable y identacion de registro de contactos
  leases/views.py
Labels: refactoring

#157 Creación de modelo y migración para crear PAGOS
  leases/migrations/0004_payments.py
  leases/models.py
Labels: enhancement

#160 API para registro de PAGOS
  leases/serializer.py
  leases/urls.py
  leases/views.py
Labels: enhancement

#162 API para Listar PAGOS por arriendo
  leases/views.py
Labels: enhancement

#164 Creación de aplicación Finanzas
  financials/__init__.py
  financials/admin.py
  financials/apps.py
  financials/migrations/__init__.py
  financials/models.py
  financials/tests.py
  financials/views.py
Labels: enhancement

#165 Eliminación de registro de pagos en la aplicación Arriendos
  leases/migrations/0004_payments.py
  leases/models.py
  leases/serializer.py
  leases/urls.py
  leases/views.py
Labels: refactoring

#167 Creación de modelos y migración de Pagos, Movimiento de Garantías y d…
  financials/migrations/0001_initial.py
  financials/models.py
Labels: enhancement

#168 API para listar y crear Pagos por arriendo
  Arriendos_Backend/urls.py
  financials/serializer.py
  financials/urls.py
  financials/views.py
Labels: refactoring

#170 Reestructuración de migraciones y modelos de Rental
  leases/migrations/0004_rental_year.py
  leases/migrations/0005_remove_rental_is_plan_remove_rental_year.py
  leases/models.py
Labels: refactoring

#172 API Rental edición de fechas de los eventos y validación de fechas
  leases/serializer.py
  leases/views.py
Labels: enhancement

#174 Requisitos entregados y generación de Formulario de reserva
  requirements.txt
  requirements/function.py
  requirements/serializer.py
  requirements/templates/reserva.html
  requirements/views.py
Labels: enhancement

#176 Validaciónes de requisitos entregados
  leases/views.py
  requirements/views.py
Labels: enhancement

#178 API para registrar montos de ingreso de garantías
  financials/serializer.py
  financials/urls.py
  financials/views.py
Labels: enhancement

#179 Adición de campo voucher en el modelo MOVIMIENTO DE GARANTÍA
  financials/migrations/0002_warranty_movement_voucher_number.py
  financials/models.py
Labels: enhancement, refactoring

#180 Adición de campo voucher en la API para registrar montos de ingreso
  financials/views.py
Labels: refactoring

#182 API para registrar descuentos por daños de evento de la Garantía
  financials/serializer.py
  financials/urls.py
  financials/views.py
Labels: enhancement

#184 API para registrar la devolución de la garantía
  financials/urls.py
  financials/views.py
Labels: enhancement

#186 API para registrar el total del Pago del Arriendo
  financials/urls.py
  financials/views.py
Labels: enhancement

#188 API Sub Ambientes de rooms
  leases/urls.py
  rooms/migrations/0002_sub_environment.py
  rooms/migrations/0003_sub_environment_quantity.py
  rooms/models.py
  rooms/serializers.py
  rooms/urls.py
  rooms/views.py
Labels: enhancement

#190 API para eliminar el ultimo registro de pago
  financials/views.py
Labels: enhancement

#192 Creación de modelo y migración de precio de horas extra
  products/migrations/0002_price_additional_hour.py
  products/models.py
Labels: enhancement

#194 Formulario de ejecución de la garantía
  financials/function.py
  financials/templates/ejecución_de_garantía.html
  financials/views.py
Labels: enhancement

#195 Refactorización de pedido de datos
  financials/views.py
Labels: refactoring

#196 Refactorización eliminación de último pago
  financials/urls.py
  financials/views.py
Labels: refactoring

#198 CRUD de horas adicionales
  products/serializers.py
  products/urls.py
  products/views.py
Labels: enhancement

#199 Refactorización de respuesta de API para listar pagos
  financials/views.py
Labels: refactoring

#201 Formulario de solicitud de devolución de garantía
  financials/function.py
  financials/templates/solicitud_devolucion_de_garantia.html
  financials/urls.py
  financials/views.py
Labels: enhancement

#203 API para obtener el precio de hora extra por producto seleccionado
  products/urls.py
  products/views.py
  rooms/models.py
Labels: enhancement
