Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Arriendos-Backend, pull requests merged in 2023-09, with the labels that each got.

#42 Creación de APIs de Requirements y estructuración de la aplicación
  plans/migrations/0001_initial.py
  plans/models.py
  plans/serializer.py
  plans/views.py
  requirements/migrations/0001_initial.py
  requirements/models.py
  requirements/serializer.py
  requirements/views.py
Labels: enhancement

#44 API planes y requisitos
  plans/views.py
  requirements/serializer.py
Labels: enhancement

#46 API para listar inmuebles con sus respectivos ambientes
  rooms/urls.py
  rooms/views.py
Labels: enhancement

#48 API token y products
  .gitignore
  login/urls.py
  login/views.py
  products/migrations/0001_initial.py
  products/models.py
  products/serializers.py
  products/urls.py
  products/views.py
  requirements/migrations/0001_initial.py
  rooms/migrations/0001_initial.py
  rooms/models.py
  users/migrations/0001_initial.py
Labels: enhancement

#49 devolución de la imagen del inmueble con la ruta completa
  rooms/views.py
Labels: duplicate

#51 Creación de Modelo Instituciones y Refactorización del modelo cliente
  customers/models.py
Labels: enhancement

#54 Modelos y migraciones actualizadas
  customers/migrations/0001_initial.py
  customers/models.py
  products/migrations/0001_initial.py
  products/models.py
  requirements/migrations/0001_initial.py
  requirements/models.py
Labels: enhancement

#56 Api de Customers, Requirements y Rates
  Arriendos_Backend/urls.py
  products/serializers.py
  products/views.py
  requirements/serializer.py
  requirements/urls.py
  requirements/views.py
Labels: enhancement

#58 API requisitos y tarifas con paginación
  products/views.py
  requirements/serializer.py
  requirements/views.py
Labels: enhancement

#59 API para crear clientes prediciendo la institución con TAG's si es el…
  customers/serializer.py
  customers/urls.py
  customers/views.py
Labels: enhancement

#61 Adición de campos create_at y is_institution en modelos de clientes
  customers/migrations/0001_initial.py
  customers/models.py
Labels: documentation

#62 Refactorización de ruta edición y borrado de rooms
  rooms/urls.py
Labels: duplicate

#63 Refactorización para listado de clientes, respuesta de listado cuando…
  customers/views.py
Labels: enhancement

#65 Reestructuración API Tarifas, clientes con edición
  requirements/migrations/0001_initial.py
  requirements/models.py
  requirements/views.py
Labels: enhancement

#67 Refactorización de modelo de productos
  products/migrations/0001_initial.py
  products/models.py
  requirements/migrations/0001_initial.py
  requirements/migrations/__init__.py
Labels: enhancement

#69 API requisitos y clientes order by
  plans/views.py
  requirements/serializer.py
  requirements/urls.py
  requirements/views.py
Labels: enhancement

#71 API's CRUD para precios
  products/serializers.py
  products/urls.py
  products/views.py
Labels: enhancement

#73 API usuarios de activación y paginación de usuarios
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement

#75 Registro de productos con precio
  products/views.py
Labels: enhancement

#77 Carga de datos iniciales de inmuebles y ambientes
  media/property_photos/CLUB_POLICIAL_LOS_OLIVOS.jpg
  media/property_photos/GRAN_HOTEL_PARIS.jpeg
  rooms/fixtures/initial_data_property.json
  rooms/fixtures/initial_data_rooms.json
Labels: enhancement

#79 API para listar Productos con precios activos
  products/serializers.py
  products/views.py
  requirements/serializer.py
Labels: enhancement
